Improve memusg

diff --git a/memusg b/memusg
--- a/memusg
+++ b/memusg
@@ -1,8 +1,13 @@
 #!/usr/bin/env bash
+#
 # https://gist.github.com/netj/526585
 # memusg -- Measure memory usage of processes
-# Usage: memusg COMMAND [ARGS]...
+# Usage: memusg [options] [--] COMMAND [ARGS]...
 #
+# Options:
+#   -h      Help
+#   -m      Constantly print memory usage to stderr
+# ===
 # Author: Jaeho Shin <netj@sparcs.org>
 # Created: 2010-08-16
 ############################################################################
@@ -22,41 +27,71 @@
 ############################################################################
 set -um
 
-# check input
-[[ $# -gt 0 ]] || { sed -n '2,/^#$/ s/^# //p' <"$0"; exit 1; }
+help() {
+	sed -n '2,/^# ===$/ s/^# =*//p' <"$0"
+	exit 1
+}
 
 # TODO support more options: peak, footprint, sampling rate, etc.
+monitor=0
+
+while getopts ":mh" opt; do
+	case $opt in
+		h)
+			help;;
+		m)
+			monitor=1;;
+		\?)
+			printf >&2 "Invalid option: -$OPTARG\n"
+			help;;
+	esac
+done
+
+shift $((OPTIND-1))
+
+# check input
+[[ $# -gt 0 ]] || { help; }
 
 pgid=$(ps -o pgid= $$)
 # make sure we're in a separate process group
 if [[ "$pgid" == "$(ps -o pgid= $(ps -o ppid= $$))" ]]; then
-    cmd=
-    set -- "$0" "$@"
-    for a; do cmd+="'${a//"'"/"'\\''"}' "; done
-    exec bash -i -c "$cmd"
+	cmd=
+	set -- "$0" "$@"
+	for a; do cmd+="'${a//"'"/"'\\''"}' "; done
+	exec bash -i -c "$cmd"
 fi
 
 # detect operating system and prepare measurement
 case $(uname) in
-    Darwin|*BSD) sizes() { /bin/ps -o rss= -g $1; } ;;
-    Linux) sizes() { /bin/ps -o rss= -$1; } ;;
-    *) echo "$(uname): unsupported operating system" >&2; exit 2 ;;
+	Darwin|*BSD) sizes() { /bin/ps -o rss= -g $1; } ;;
+	Linux) sizes() { /bin/ps -o rss= -$1; } ;;
+	*) echo "$(uname): unsupported operating system" >&2; exit 2 ;;
 esac
+
+sum_expr() { echo ${@/#/+}; }
 
 # monitor the memory usage in the background.
 (
 peak=0
 while sizes=$(sizes $pgid)
 do
-    set -- $sizes
-    sample=$((${@/#/+}))
-    let peak="sample > peak ? sample : peak"
-    sleep 0.1
+	sample=$(($(sum_expr $sizes)))
+	peak=$((sample > peak ? sample : peak))
+
+	if [[ "$monitor" = "1" ]]; then
+		printf >&2 "\rmemusg: peak=%s" "$peak"
+	fi
+
+	sleep 0.1
 done
-echo "memusg: peak=$peak" >&2
+
+if [[ "$monitor" != "1" ]]; then
+	printf >&2 "\nmemusg: peak=%s" "$peak"
+fi
+
+printf >&2 "\n"
 ) &
 monpid=$!
-
 
 # run the given command
 exec "$@"
